// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudIA.Data;

#nullable disable

namespace StudIA.Data.Migrations
{
    [DbContext(typeof(StudIAContext))]
    [Migration("20260420201231_MigracionDiccionarioDatosV2")]
    partial class MigracionDiccionarioDatosV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apunte", b =>
                {
                    b.Property<int>("IdApunte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_apunte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApunte"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdApunte");

                    b.HasIndex("IdMateria");

                    b.ToTable("Apuntes");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_materia");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            IdMateria = 1,
                            Descripcion = "Proyecto StudIA",
                            IdUsuario = 1,
                            NombreMateria = "Ingeniería de Software II"
                        },
                        new
                        {
                            IdMateria = 2,
                            Descripcion = "Preparación de finales",
                            IdUsuario = 1,
                            NombreMateria = "Cálculo"
                        },
                        new
                        {
                            IdMateria = 3,
                            Descripcion = "Modelos probabilísticos",
                            IdUsuario = 1,
                            NombreMateria = "Estadística"
                        });
                });

            modelBuilder.Entity("Pomodoro", b =>
                {
                    b.Property<int>("IdPomodoro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pomodoro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPomodoro"));

                    b.Property<int>("DuracionDescanso")
                        .HasColumnType("int")
                        .HasColumnName("duracion_descanso");

                    b.Property<int>("DuracionEstudio")
                        .HasColumnType("int")
                        .HasColumnName("duracion_estudio");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdApunte")
                        .HasColumnType("int")
                        .HasColumnName("id_apunte");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdPomodoro");

                    b.HasIndex("IdApunte");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pomodoros");
                });

            modelBuilder.Entity("Progreso", b =>
                {
                    b.Property<int>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_progreso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgreso"));

                    b.Property<float>("AvancePorcentual")
                        .HasColumnType("real")
                        .HasColumnName("avance_porcentual");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdProgreso");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Progresos");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "1234",
                            Correo = "wilson@test.com",
                            Nombre = "Wilson Merlo"
                        });
                });

            modelBuilder.Entity("Apunte", b =>
                {
                    b.HasOne("Materia", "Materia")
                        .WithMany("Apuntes")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.HasOne("StudIA.Data.Entities.Usuario", "Usuario")
                        .WithMany("Materias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pomodoro", b =>
                {
                    b.HasOne("Apunte", "Apunte")
                        .WithMany()
                        .HasForeignKey("IdApunte");

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudIA.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apunte");

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Progreso", b =>
                {
                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudIA.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.Navigation("Apuntes");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
