// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudIA.Data;

#nullable disable

namespace StudIA.Data.Migrations
{
    [DbContext(typeof(StudIAContext))]
    partial class StudIAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudIA.Data.Entities.Apunte", b =>
                {
                    b.Property<int>("IdApunte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApunte"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("MateriaIdMateria")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdApunte");

                    b.HasIndex("MateriaIdMateria");

                    b.ToTable("Apuntes");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            IdMateria = 1,
                            Descripcion = "Proyecto StudIA",
                            IdUsuario = 1,
                            NombreMateria = "Ingeniería de Software II"
                        },
                        new
                        {
                            IdMateria = 2,
                            Descripcion = "Preparación de finales",
                            IdUsuario = 1,
                            NombreMateria = "Cálculo"
                        },
                        new
                        {
                            IdMateria = 3,
                            Descripcion = "Modelos probabilísticos",
                            IdUsuario = 1,
                            NombreMateria = "Estadística"
                        });
                });

            modelBuilder.Entity("StudIA.Data.Entities.Pomodoro", b =>
                {
                    b.Property<int>("IdPomodoro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPomodoro"));

                    b.Property<int?>("ApunteIdApunte")
                        .HasColumnType("int");

                    b.Property<int>("DuracionDescanso")
                        .HasColumnType("int");

                    b.Property<int>("DuracionEstudio")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdApunte")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("MateriaIdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdPomodoro");

                    b.HasIndex("ApunteIdApunte");

                    b.HasIndex("MateriaIdMateria");

                    b.ToTable("Pomodoros");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Progreso", b =>
                {
                    b.Property<int>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgreso"));

                    b.Property<float>("AvancePorcentual")
                        .HasColumnType("real");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("MateriaIdMateria")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdProgreso");

                    b.HasIndex("MateriaIdMateria");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Progresos");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "1234",
                            Correo = "wilson@test.com",
                            Nombre = "Wilson Merlo"
                        });
                });

            modelBuilder.Entity("StudIA.Data.Entities.Apunte", b =>
                {
                    b.HasOne("StudIA.Data.Entities.Materia", "Materia")
                        .WithMany("Apuntes")
                        .HasForeignKey("MateriaIdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Materia", b =>
                {
                    b.HasOne("StudIA.Data.Entities.Usuario", "Usuario")
                        .WithMany("Materias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Pomodoro", b =>
                {
                    b.HasOne("StudIA.Data.Entities.Apunte", "Apunte")
                        .WithMany()
                        .HasForeignKey("ApunteIdApunte");

                    b.HasOne("StudIA.Data.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaIdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apunte");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Progreso", b =>
                {
                    b.HasOne("StudIA.Data.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaIdMateria");

                    b.HasOne("StudIA.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Materia", b =>
                {
                    b.Navigation("Apuntes");
                });

            modelBuilder.Entity("StudIA.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
